# Generated by Django 2.0.7 on 2018-08-09 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pastor_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('video_url', models.URLField()),
                ('image_url', models.URLField()),
                ('date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sermons.Serie')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
