# Generated by Django 2.0.7 on 2018-08-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='description',
            field=models.TextField(),
        ),
    ]
