# Generated by Django 2.0.7 on 2018-08-06 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='owner',
        ),
    ]
