# Generated by Django 2.0.7 on 2018-08-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slogan', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('main_pastor', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('logo_url', models.URLField()),
                ('website_url', models.URLField()),
                ('facebook_url', models.URLField()),
                ('twitter_url', models.URLField()),
                ('instagram_url', models.URLField()),
                ('youtube_url', models.URLField()),
                ('snapchat_url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
